  - platform: template
    id: ${device_id}_health_mode
    name: Health mode
    icon: mdi:leaf
    restore_state: yes
    lambda: |-
      return id(${device_id}).get_health_mode();
    turn_on_action:
      climate.haier.health_on: ${device_id}
    turn_off_action:
      climate.haier.health_off: ${device_id}
