substitutions:
  device_name: Haier AC
  device_id: haier_climate
  uart_id: ac_port 

esphome:
  name: haier
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

uart:
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 16
  id: ${uart_id}  

logger:
  level: DEBUG

<<: !include .haier-hon-base.yaml
