substitutions:
  device_name: Haier AC

esphome:
  name: haier
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

external_components:
  source:
    type: local
    path: ./components

uart:
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 16
  id: ac_port  
    
logger:
  level: DEBUG
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
api:

ota:

climate:
  - platform: haier
    name: ${device_name} 
    uart_id: ac_port
    wifi_signal: true
    outdoor_temperature:        # Optional outdoor temperature sensor. Shows incorrect values when AC is not active for a long time
      name: ${device_name} outdoor temperature