esphome:
  name: haier
  name_add_mac_suffix: true
  includes:
    - src/HaierPacket.h
    - src/HaierClimate.h
    - src/HaierClimate.cpp
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

uart:
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 16
  id: ac_port  
    
logger:
  level: DEBUG
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
api:

ota:
  
climate:
  - platform: custom
    lambda: |-
      auto haier = new HaierClimate(id(ac_port));
      App.register_component(haier);
      return {haier};
    climates:
      - name: "Haier AC"