substitutions:
  device_name: Haier AC

esphome:
  name: haier
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

external_components:
  source:
    type: local
    path: ./components

uart:
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 16
  id: ac_port  
    
logger:
  level: DEBUG
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
api:

ota:

climate:
  - platform: haier
    id: haier_climate
    name: ${device_name} 
    uart_id: ac_port
    wifi_signal: true           # Optional, default true, enables WiFI signal transmission from ESP to AC
    beeper: true                # Optional, default true, disables beep on commands from ESP
    use_fahrenheit: false       # Optional, default false, only for AC screen
    outdoor_temperature:        # Optional, outdoor temperature sensor
      name: ${device_name} outdoor temperature

switch:
  - platform: template
    id: haier_climate_display_switch
    name: ${device_name} display
    icon: mdi:led-on
    restore_state: true
    optimistic: true
    assumed_state: true
    turn_on_action:
      climate.haier.display_on: haier_climate
    turn_off_action:
      climate.haier.display_off: haier_climate
  - platform: template
    id: haier_climate_beeper_switch
    name: ${device_name} beeper
    icon: mdi:volume-high
    restore_state: true
    optimistic: true
    assumed_state: true
    turn_on_action:
      climate.haier.beeper_on: haier_climate
    turn_off_action:
      climate.haier.beeper_off: haier_climate
