substitutions:
  device_name: Attic room AC
  device_id: haier_climate
  send_wifi: "true"
  uart_id: ac_port
  errors_counter: errors_counter
  reboots_counter: reboots_counter
  warnings_counter: warnings_counter

globals:
  - <<: !include configs/globals/reboots_counter.yaml
  - <<: !include configs/globals/warnings_counter.yaml
  - <<: !include configs/globals/errors_counter.yaml

esphome:
  name: haier
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    - <<: !include configs/core/reboots_counter_increase.yaml

esp32:
  board: esp32-c3-devkitm-1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  baud_rate: 9600
  tx_pin: 19
  rx_pin: 18
  id: ${uart_id}

web_server:

logger:
  level: VERBOSE
  on_message:
    - <<: !include configs/logger/warnings_counter_increase.yaml
    - <<: !include configs/logger/errors_counter_increase.yaml

sensor:
  - <<: !include configs/sensor/reboots_counter.yaml
  - <<: !include configs/sensor/warnings_counter.yaml
  - <<: !include configs/sensor/errors_counter.yaml

<<: !include .haier-hon-base.yaml

switch:
  - <<: !include configs/switch/display.yaml
  - <<: !include configs/switch/beeper.yaml
  - <<: !include configs/switch/health_mode.yaml
  - <<: !include configs/switch/restart.yaml
  - platform: template
    id: ${device_id}_send_wifi
    name: ${device_name} send WiFi
    optimistic: yes
    restore_mode:  RESTORE_DEFAULT_ON
    turn_on_action:
      then:
        - lambda: id(${device_id}).set_send_wifi(true);
    turn_off_action:
      then:
        - lambda: id(${device_id}).set_send_wifi(false);
