substitutions:
  device_name: Haier AC
  device_id: haier_climate
  uart_id: ac_port 

esphome:
  name: haier
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

logger:
  level: DEBUG

uart:
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 16
  id: ${uart_id}  

<<: !include .haier-base.yaml
