substitutions:
  device_name: Haier AC
  device_id: haier_climate
  uart_id: ac_port 

esphome:
  name: haier
  name_add_mac_suffix: true

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

logger:
  level: DEBUG

uart:
  baud_rate: 9600
  id: ${uart_id}  
  tx_pin: GPIO0
  rx_pin: GPIO1

<<: !include .haier-hon-base.yaml
