substitutions:
  device_name: Haier AC
  device_id: haier_climate
  uart_id: ac_port 

esphome:
  name: haier
  name_add_mac_suffix: true

esp8266:
  board: d1_mini

uart:
  - id: ${uart_id}  
    baud_rate: 9600
    # You can also use pins 15 (TX) and 13 (RX)
    tx_pin: 1
    rx_pin: 3

logger:
  level: DEBUG
  baud_rate: 0
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
web_server:

<<: !include .haier-base.yaml
