# Introduced in (some) models starting from 2021
  - platform: template
    name: Start 56°C steri-cleaning
    icon: mdi:spray-bottle
    on_press:
      -  climate.haier.start_steri_cleaning: ${device_id}
